export default [
    {
        id: 1,
        thumbhnailBlog: "./src/assets/images/thumbnail-danau-toba-indah.png",
        thumbhnailBlogTwo: "./src/assets/images/thumbnail-sumbar.webp",
        thumbhnailBlogTree: "./src/assets/images/thumbnail-sumbar.webp",
        title: "Keindahan Danau Toba, Surga di Tanah Batak 1",
        description: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi.",
        descriptionDetailOne: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi.",
        descriptionDetailTwo: "Danau Toba bukan hanya sekedar danau besar, melainkan sebuah kawasan dengan kekayaan alam dan budaya yang luar biasa. Terbentuk dari letusan gunung berapi ribuan tahun lalu, Danau Toba memiliki panjang 100 kilometer dan lebar 30 kilometer, dengan Pulau Samosir yang terletak di tengahnya. Keindahan alam yang memukau, mulai dari perbukitan hijau yang mengelilingi danau hingga airnya yang jernih, membuat siapapun yang mengunjungi tempat ini merasa takjub. Udara sejuk pegunungan menambah kenyamanan, menjadikan Danau Toba sebagai tempat yang ideal untuk bersantai dan menikmati pemandangan. Di Pulau Samosir, pengunjung dapat menemukan jejak-jejak budaya Batak, dengan rumah-rumah tradisional dan makam batu yang menceritakan kisah sejarah suku tersebut. Menjelajahi pulau ini, wisatawan dapat memahami lebih dalam budaya dan tradisi lokal yang kental di Tanah Batak.",
        descriptionDetailTree: "Selain keindahan alamnya, Danau Toba juga dikenal dengan sejarah dan legenda yang melekat erat. Menurut cerita rakyat, danau ini terbentuk dari air mata seorang pria bernama Toba yang kehilangan anak dan istrinya akibat kutukan. Legenda ini menjadikan Danau Toba tidak hanya indah secara visual, tetapi juga memiliki nilai historis dan spiritual yang mendalam. Hingga kini, Danau Toba tetap menjadi salah satu destinasi utama di Indonesia yang menawarkan pengalaman wisata alam yang lengkap, mulai dari keindahan, ketenangan, hingga kekayaan budaya yang tak tertandingi.",
        descriptionFour: "Mengunjungi Danau Toba bukan hanya sekadar perjalanan wisata, tetapi juga sebuah kesempatan untuk merenungkan betapa kayanya alam Indonesia. Keindahan dan kedamaian yang ditawarkan Danau Toba adalah pengingat bagi kita semua akan pentingnya menjaga dan melestarikan kekayaan alam yang dimiliki negeri ini. Dengan tetap mempertahankan kelestarian Danau Toba, kita turut menjaga warisan alam dan budaya yang tak ternilai ini bagi generasi mendatang.",
        viewCount: 100,
        date: "29 Juli 2024",
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 2,
        thumbhnailBlog: "./src/assets/images/thumbnail-danau-toba-indah.png",
        thumbhnailBlogTwo: "./src/assets/images/thumbnail-danau-toba-indah.png",
        thumbhnailBlogTree: "./src/assets/images/thumbnail-sumbar.webp",
        title: "Keindahan Danau Toba, Surga di Tanah Batak 2",
        description: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi. dwdwd wdddw dwd wddwdwdwddwd dwdwdwdwddwd",
        descriptionDetailOne: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi.",
        descriptionDetailTwo: "Danau Toba bukan hanya sekedar danau besar, melainkan sebuah kawasan dengan kekayaan alam dan budaya yang luar biasa. Terbentuk dari letusan gunung berapi ribuan tahun lalu, Danau Toba memiliki panjang 100 kilometer dan lebar 30 kilometer, dengan Pulau Samosir yang terletak di tengahnya. Keindahan alam yang memukau, mulai dari perbukitan hijau yang mengelilingi danau hingga airnya yang jernih, membuat siapapun yang mengunjungi tempat ini merasa takjub. Udara sejuk pegunungan menambah kenyamanan, menjadikan Danau Toba sebagai tempat yang ideal untuk bersantai dan menikmati pemandangan. Di Pulau Samosir, pengunjung dapat menemukan jejak-jejak budaya Batak, dengan rumah-rumah tradisional dan makam batu yang menceritakan kisah sejarah suku tersebut. Menjelajahi pulau ini, wisatawan dapat memahami lebih dalam budaya dan tradisi lokal yang kental di Tanah Batak.",
        descriptionDetailTree: "Selain keindahan alamnya, Danau Toba juga dikenal dengan sejarah dan legenda yang melekat erat. Menurut cerita rakyat, danau ini terbentuk dari air mata seorang pria bernama Toba yang kehilangan anak dan istrinya akibat kutukan. Legenda ini menjadikan Danau Toba tidak hanya indah secara visual, tetapi juga memiliki nilai historis dan spiritual yang mendalam. Hingga kini, Danau Toba tetap menjadi salah satu destinasi utama di Indonesia yang menawarkan pengalaman wisata alam yang lengkap, mulai dari keindahan, ketenangan, hingga kekayaan budaya yang tak tertandingi.",
        descriptionFour: "Mengunjungi Danau Toba bukan hanya sekadar perjalanan wisata, tetapi juga sebuah kesempatan untuk merenungkan betapa kayanya alam Indonesia. Keindahan dan kedamaian yang ditawarkan Danau Toba adalah pengingat bagi kita semua akan pentingnya menjaga dan melestarikan kekayaan alam yang dimiliki negeri ini. Dengan tetap mempertahankan kelestarian Danau Toba, kita turut menjaga warisan alam dan budaya yang tak ternilai ini bagi generasi mendatang.",
        viewCount: 140,
        date: "29 Juli 2024",
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 3,
        thumbhnailBlog: "./src/assets/images/thumbnail-danau-toba-indah.png",
        thumbhnailBlogTwo: "./src/assets/images/thumbnail-danau-toba-indah.png",
        thumbhnailBlogTree: "./src/assets/images/thumbnail-sumbar.webp",
        title: "Keindahan Danau Toba, Surga di Tanah Batak 3",
        description: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi.",
        descriptionDetailOne: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi.",
        descriptionDetailTwo: "Danau Toba bukan hanya sekedar danau besar, melainkan sebuah kawasan dengan kekayaan alam dan budaya yang luar biasa. Terbentuk dari letusan gunung berapi ribuan tahun lalu, Danau Toba memiliki panjang 100 kilometer dan lebar 30 kilometer, dengan Pulau Samosir yang terletak di tengahnya. Keindahan alam yang memukau, mulai dari perbukitan hijau yang mengelilingi danau hingga airnya yang jernih, membuat siapapun yang mengunjungi tempat ini merasa takjub. Udara sejuk pegunungan menambah kenyamanan, menjadikan Danau Toba sebagai tempat yang ideal untuk bersantai dan menikmati pemandangan. Di Pulau Samosir, pengunjung dapat menemukan jejak-jejak budaya Batak, dengan rumah-rumah tradisional dan makam batu yang menceritakan kisah sejarah suku tersebut. Menjelajahi pulau ini, wisatawan dapat memahami lebih dalam budaya dan tradisi lokal yang kental di Tanah Batak.",
        descriptionDetailTree: "Selain keindahan alamnya, Danau Toba juga dikenal dengan sejarah dan legenda yang melekat erat. Menurut cerita rakyat, danau ini terbentuk dari air mata seorang pria bernama Toba yang kehilangan anak dan istrinya akibat kutukan. Legenda ini menjadikan Danau Toba tidak hanya indah secara visual, tetapi juga memiliki nilai historis dan spiritual yang mendalam. Hingga kini, Danau Toba tetap menjadi salah satu destinasi utama di Indonesia yang menawarkan pengalaman wisata alam yang lengkap, mulai dari keindahan, ketenangan, hingga kekayaan budaya yang tak tertandingi.",
        descriptionFour: "Mengunjungi Danau Toba bukan hanya sekadar perjalanan wisata, tetapi juga sebuah kesempatan untuk merenungkan betapa kayanya alam Indonesia. Keindahan dan kedamaian yang ditawarkan Danau Toba adalah pengingat bagi kita semua akan pentingnya menjaga dan melestarikan kekayaan alam yang dimiliki negeri ini. Dengan tetap mempertahankan kelestarian Danau Toba, kita turut menjaga warisan alam dan budaya yang tak ternilai ini bagi generasi mendatang.",
        viewCount: 140,
        date: "29 Juli 2024",
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 4,
        thumbhnailBlog: "./src/assets/images/thumbnail-danau-toba-indah.png",
        thumbhnailBlogTwo: "./src/assets/images/thumbnail-danau-toba-indah.png",
        thumbhnailBlogTree: "./src/assets/images/thumbnail-sumbar.webp",
        title: "Keindahan Danau Toba, Surga di Tanah Batak 3",
        description: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi.",
        descriptionDetailOne: "Danau Toba, sebuah keajaiban alam di Sumatera Utara, merupakan salah satu danau vulkanik terbesar di dunia. Selain ukurannya yang mengesankan, keindahan alam di sekitarnya serta legenda yang menyelimutinya menjadikan Danau Toba sebagai destinasi yang wajib dikunjungi.",
        descriptionDetailTwo: "Danau Toba bukan hanya sekedar danau besar, melainkan sebuah kawasan dengan kekayaan alam dan budaya yang luar biasa. Terbentuk dari letusan gunung berapi ribuan tahun lalu, Danau Toba memiliki panjang 100 kilometer dan lebar 30 kilometer, dengan Pulau Samosir yang terletak di tengahnya. Keindahan alam yang memukau, mulai dari perbukitan hijau yang mengelilingi danau hingga airnya yang jernih, membuat siapapun yang mengunjungi tempat ini merasa takjub. Udara sejuk pegunungan menambah kenyamanan, menjadikan Danau Toba sebagai tempat yang ideal untuk bersantai dan menikmati pemandangan. Di Pulau Samosir, pengunjung dapat menemukan jejak-jejak budaya Batak, dengan rumah-rumah tradisional dan makam batu yang menceritakan kisah sejarah suku tersebut. Menjelajahi pulau ini, wisatawan dapat memahami lebih dalam budaya dan tradisi lokal yang kental di Tanah Batak.",
        descriptionDetailTree: "Selain keindahan alamnya, Danau Toba juga dikenal dengan sejarah dan legenda yang melekat erat. Menurut cerita rakyat, danau ini terbentuk dari air mata seorang pria bernama Toba yang kehilangan anak dan istrinya akibat kutukan. Legenda ini menjadikan Danau Toba tidak hanya indah secara visual, tetapi juga memiliki nilai historis dan spiritual yang mendalam. Hingga kini, Danau Toba tetap menjadi salah satu destinasi utama di Indonesia yang menawarkan pengalaman wisata alam yang lengkap, mulai dari keindahan, ketenangan, hingga kekayaan budaya yang tak tertandingi.",
        descriptionFour: "Mengunjungi Danau Toba bukan hanya sekadar perjalanan wisata, tetapi juga sebuah kesempatan untuk merenungkan betapa kayanya alam Indonesia. Keindahan dan kedamaian yang ditawarkan Danau Toba adalah pengingat bagi kita semua akan pentingnya menjaga dan melestarikan kekayaan alam yang dimiliki negeri ini. Dengan tetap mempertahankan kelestarian Danau Toba, kita turut menjaga warisan alam dan budaya yang tak ternilai ini bagi generasi mendatang.",
        viewCount: 140,
        date: "29 Juli 2024",
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
];