export default [
    {
        id: 1, 
        name: "Kelingking Beach",
        category: "Alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 150000,
        rating: 4.3,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 2, 
        name: "Kelingking Beach",
        category: "Alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 300000,
        rating: 4.8,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 3, 
        name: "Kelingking Beach",
        category: "Alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 240000,
        rating: 3,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 4, 
        name: "Kelingking Beach",
        category: "Alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 5, 
        name: "Kelingking Beach",
        category: "Alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 6, 
        name: "Kelingking Beach",
        category: "Alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
];