export default [
    {
        id: 1, 
        name: "Ini Bali",
        category: "alam", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        thumbnailProvince: "/src/assets/images/thumbnail-bali.webp",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 150000,
        rating: 4.3,
        viewCount: 1000,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 2, 
        name: "Ini Jateng",
        category: "alam", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        thumbnailProvince: "./src/assets/images/thumbnail-jateng.webp",
        description: "This is a description",
        province: "Jawa Tengah",
        location: "Semarang",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 300000,
        rating: 4.8,
        viewCount: 1000,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 3, 
        name: "Ini Jabar",
        category: "sejarah", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Jawa Barat",
        location: "Rengasdengklok, Kerawang",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 240000,
        rating: 3,
        viewCount: 436,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 4, 
        name: "Ini Maluku",
        category: "sejarah", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Maluku",
        location: "Ambon",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 23,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 5, 
        name: "Ini Jatim",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Jawa Timur",
        location: "Malang",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 1,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 6, 
        name: "Ini NTB",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Nusa Tenggara Barat",
        location: "Lombok",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 920,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 7, 
        name: "Ini Sumbar",
        category: "alam", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Sumatera Barat",
        location: "Bukit tinggi",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 543,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 8, 
        name: "Ini Bangbel",
        category: "alam", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Bangka Belitung",
        location: "Belitung",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 2001,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 9, 
        name: "Ini Kalsel",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Kalimantan Selatan",
        location: "Banjarmasin",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 63,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 10, 
        name: "Ini Papua",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Papua",
        location: "Jayapura",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 874,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 11, 
        name: "Ini Sulut",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Sulawesi Utara",
        location: "Manado",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 220,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 12, 
        name: "Ini Sulsel",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.webp",
        description: "This is a description",
        province: "Sulawesi Selatan",
        location: "Makassar",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 10,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    }
];