export default [
    {
        id: 1, 
        name: "Kelingking Beach",
        category: "alam", 
        thumbnail: "./src/assets/images/card-kelingking.png",
        thumbnailProvince: "./src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 150000,
        rating: 4.3,
        viewCount: 1000,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 2, 
        name: "Gunung Selamet",
        category: "alam", 
        thumbnail: "./src/assets/images/card-kelingking.png",
        thumbnailProvince: "./src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Jawa tengah",
        location: "Gunungsari, Pemalang",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 300000,
        rating: 4.8,
        viewCount: 34,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 3, 
        name: "Monumen Kebulatan Tekad",
        category: "sejarah", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Jawa Barat",
        location: "Rengasdengklok, Kerawang",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 240000,
        rating: 3,
        viewCount: 436,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 4, 
        name: "Monumen Nasional",
        category: "sejarah", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Jakarta",
        location: "Jakarta Pusat",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 23,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 5, 
        name: "Museum Ganesya",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Jawa Timus",
        location: "Malang",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 1,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 6, 
        name: "Museum Agung Rai",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Bali",
        location: "Ubud",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 920,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 7, 
        name: "Gunung Kerinci",
        category: "alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Sumatra Barat",
        location: "Jambi",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 543,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 8, 
        name: "Gunung Rinjani",
        category: "alam", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "NTB",
        location: "Sembalun, Lombok Timur",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 2001,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    
    {
        id: 9, 
        name: "Kelingki",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 63,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    
    {
        id: 10, 
        name: "Kelingking Beach",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 874,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 11, 
        name: "Kelingking Beach",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 220,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    },
    {
        id: 11, 
        name: "Kelingking Beach",
        category: "kesenian", 
        thumbnail: "/src/assets/images/card-kelingking.png",
        thumbnailProvince: "/src/assets/images/card-province-placeir.png",
        description: "This is a description",
        province: "Bali",
        location: "Nusa Penida, Bali",
        locationLink: "https://maps.app.goo.gl/PHCgoG8gmPksbWiU9",
        price: 250000,
        rating: 4,
        viewCount: 10,
        createdAt: "2023-11-15 10:21:37.261134+01:00"
    }
];